source "$HOME/.local/share/zinit/zinit.git/zinit.zsh"
export XDG_CONFIG_HOME="$HOME/.config"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
zinit light-mode for \
    zdharma-continuum/zinit-annex-as-monitor \
    zdharma-continuum/zinit-annex-bin-gem-node \
    zdharma-continuum/zinit-annex-patch-dl \
    zdharma-continuum/zinit-annex-rust

### End of Zinit's installer chunk

# zinit plugins
zinit light zsh-users/zsh-autosuggestions
zinit light zsh-users/zsh-syntax-highlighting
zinit light zdharma/history-search-multi-word

# Aliases
alias g='git'
alias n='nvim'
alias lg='lazygit'
alias sa='cd /path/to/SA'
alias ~='cd ~'
alias ..='cd ..'

# Functions
cdBack() {
  cd ..
}

showGitDiff() {
  git diff -w
}

add_space() {
    echo ""
}

autoload -Uz compinit && compinit
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'


typeset -a preexec_functions
preexec_functions+=(add_space)

# FZF keybindings for Arch
source /usr/share/fzf/key-bindings.zsh
source /usr/share/fzf/completion.zsh

bindkey '^T' fzf-file-widget
bindkey '^R' fzf-history-widget

eval "$(starship init zsh)"
