# eval "$(oh-my-posh init zsh --config ~/.dotfiles/ohmyposh/config.yaml)"
eval "$(oh-my-posh init zsh --config ~/.dotfiles/ohmyposh/catppuccin.yaml)"
enable_poshtransientprompt

source $(brew --prefix)/opt/zinit/zinit.zsh
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

zinit light zsh-users/zsh-autosuggestions
zinit light zsh-users/zsh-syntax-highlighting
zinit light zdharma/history-search-multi-word

alias g='git'
alias n='nvim'
alias lg='lazygit'
alias sa='cd /path/to/SA'
alias ~='cd ~'
alias ..='cd ..'
alias ls='lsd'

cdBack() {
  cd ..
}

showGitDiff() {
  git diff -w
}

add_space() {
	echo ""
}

typeset -a preexec_functions

preexec_functions+=(add_space)


# fzf

if [ -f $(brew --prefix)/opt/fzf/shell/completion.zsh ]; then
  source $(brew --prefix)/opt/fzf/shell/completion.zsh
fi

if [ -f $(brew --prefix)/opt/fzf/shell/key-bindings.zsh ]; then
  source $(brew --prefix)/opt/fzf/shell/key-bindings.zsh
fi

bindkey '^T' fzf-file-widget
bindkey '^R' fzf-history-widget

export FZF_DEFAULT_OPTS="--height 40% --layout=reverse --border"
export FZF_DEFAULT_COMMAND="fd --type file --follow --hidden --exclude .git"
export GOROOT=/opt/homebrew/Cellar/go/1.22.0/libexec
export PATH=$PATH:$GOROOT/bin
